Made dev runnable on Windows (fixed setting env var, added missing package)
Environment vars syntax wasn't suitable for Windows, also spaces had to be
removed (as recommended here: https://github.com/facebook/create-react-app/issues/873#issuecomment-396803278).

After managing to show Electron app withouth just a white blank screen, it was
complaining about "TypeError: inline_style_prefixer_1.prefix is not a function",
so I added that package.